apiVersion: v1
kind: Service
metadata:  
  labels:
    app: deploy-pgadmin
    env: prod
  name: svc-nodeport-pgadmin
  namespace: ic-webapp
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30007

  selector:
    app: deploy-pgadmin
status:
  loadBalancer: {}