apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deploy-bdd
    env: prod
  name: svc-clusterip-bdd
  namespace: ic-webapp
spec:
  ports:
  - port: 8069
    protocol: TCP
    targetPort: 5432
    

  selector:
    app: deploy-bdd
status:
  loadBalancer: {}
