apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deploy-bdd
    env: prod
  name: svc-clusterip-bdd
  namespace: ns-icwebapp
spec:
  ports:
  - port: 8069
    protocol: TCP
    targetPort: 8069
    

  selector:
    app: deploy-odoo
status:
  loadBalancer: {}