apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy-ic-webapp
    env: prod
  name: deploy-ic-webapp
  namespace: ic-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-ic-webapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-ic-webapp
    spec:
      containers:
      - image: linanzouechim/ic-webapp:1.0
        name: ic-webapp
        env:
        - name: ODOO_URL
          value: http://192.31.245.8:30009
        - name: PGADMIN_URL
          value: http://192.31.245.8:30007
        ports:
        - containerPort: 8080
      

status: {}
