apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deploy-ic-webapp
    env: prod
  name: svc-nodeport-icwebapp
  namespace: ic-webapp
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30010
  selector:
    app: deploy-ic-webapp
status:
  loadBalancer: {}
