apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deploy-odoo
    env: prod
  name: svc-odoo
  namespace: ic-webapp
spec:
  type: NodePort
  ports:
  - port: 8069
    protocol: TCP
    targetPort: 8069
    nodePort: 30009

  selector:
    app: deploy-odoo
status:
  loadBalancer: {}
